

services:
  loki:
    image: grafana/loki:2.4.1
    ports:
      - 3100:3100
    volumes:
      - ./metrics:/var/log
      - ./config:/mnt/config
    command: "-config.file=/mnt/config/loki-config.yml"
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./metrics:/var/log
      - ./config:/mnt/config
    command: "-config.file=/mnt/config/promtail-config.yml"
    ports:
      - "9080:9080"
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '0'
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-storage:/var/lib/grafana:rw
    networks:
      - loki
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
# volumes:
#   grafana-storage: {}
networks:
  loki: