server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: "/mnt/config/positions.yml"

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: highscore-db-performance
    pipeline_stages:
      - json:
          expressions:
            key:
            value:
            _time:
            _id:
            _implementation:
      - labels:
          key:
          _id:
          _implementation:
      - timestamp:
          source: _time
          format: Unix
    static_configs:
      - targets:
          - localhost
        labels:
          job: ccglogprd
          __path__: /var/log/*.log
