server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: "/mnt/config/positions.yml"

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: jsonl-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jsonl-logs
          __path__: /var/log/*.jsonl
    pipeline_stages:
      - json:
          expressions:
            key: key
            value: value
            time: _time
            id: _id
            implementation: _implementation

      - timestamp:
          source: time
          format: Unix

      - labels:
          key: key
          id: id
          implementation: implementation
